export const DEFAULT_START_KEY = "DEFAULT_START";
export const PROVIDE_APP_DATA_KEY = "PROVIDE_APP_DATA";
export const PROVIDE_USE_MESSAGE_KEY = "USE_MESSAGE";
export const SETTING_DATA_KEY = "SETTING_DATA";
export const FREQUENTLY_USED_BOOKMARKS_KEY = "FREQUENTLY_USED_BOOKMARKS";